Feat: Add data transformations.
prometheus-community/json_exporter pull request #333
Opened 2024-10-01 16:13 UTC by MattK360

Add transformation feature.

Addresses issue documented here: https://github.com/prometheus-community/json_exporter/pull/133

Allows for json object to get filtered by JQ before the json path is applied.

2024-10-04 05:46 UTC, chriswiggins commented
This is working perfectly for our use case. Massive +1! 👍

2024-10-18 07:26 UTC, SuperQ requested changes
This is pretty interesting. Can you rebase this now that #334 is merged and we're using `log/slog` for logging.

2026-07-27 14:22 UTC, Ekkisleif commented
@MattK360 do you have time to rebase the PR as it would be great to have this implemented on the exporter. If not, I can also take time to migrate what you already done :)

2026-08-25 12:02 UTC, ArthurSens commented
Closing since it has been a very long time without activity

2026-08-25 12:02 UTC, closed without merging